### ISSUE TITLE
docker-compose version incompatible with docker-compose.yml

### ISSUE THREAD

**Issue by pwnage101** [openedx/course-discovery#205]
docker-compose <1.6.0 gets installed, but the docker-compose.yml uses version 2 of the configuration format which requires docker-compose >= 1.6.0.

docker-compose version which gets installed: https://github.com/edx/course-discovery/blob/3770f725/requirements/local.txt#L12
configuration version: https://github.com/edx/course-discovery/blob/3770f725/docker-compose.yml#L1
compatibility documentation: https://docs.docker.com/compose/compose-file/#version-2

I upgraded to docker-compose 1.6.0 and it seems to work (before it complained that "version" is not a service, or something).

**Comment by pwnage101** [comment]
@clintonb

**Comment by pwnage101** [comment]
perhaps @edx/ecommerce is more appropriate, i was just looking at commit counts.

**Comment by clintonb** [comment]
@pwnage101 please open a pull-request, and I'll review.

**Comment by pwnage101** [comment]
addressed in 3ae64d5c54eb798f57c2745f2cd26dfb38da886f
