### ISSUE TITLE
[course-discovery] Test Python 3.11 and 3.12

### ISSUE THREAD

**Issue by feanil** [openedx/course-discovery#4307]
We should ideally aim for python 3.12 but if there are major issues, we should fall back to 3.11

**Comment by ichintanjoshi** [comment]
assign me

**Comment by DawoudSheraz** [comment]
It seems the dockerfile updates would be needed in some capacity https://github.com/openedx/course-discovery/pull/4320#issuecomment-2056737242

**Comment by feanil** [comment]
@ichintanjoshi will you have an update PR for this today? I'd like to land it soon if possible.

**Comment by DawoudSheraz** [comment]
Soban's PR is already up for that https://github.com/openedx/course-discovery/pull/4328. It should do the trick.

**Comment by ichintanjoshi** [comment]
> @ichintanjoshi will you have an update PR for this today? I'd like to land it soon if possible.

Hey @feanil  as @DawoudSheraz  mentioned and as @iamsobanjaved has already done work in #4328 I am not sure if there is anything more to be done.
